apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: bgd
spec:
  host: bgd.apps.openshift.devops.philips-healthsuitechina.com.cn
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: bgd
    weight: 100
  wildcardPolicy: None